/**
 * Client-side PDF generation for Therapist Bridge briefs.
 * Uses pdf-lib (pure JS, no native deps).
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export interface MoodArcPoint {
  date: string;
  intensity_score: number;
  clarity_score: number;
}

export interface RepresentativeEntry {
  journal_id: string;
  date: string;
  summary: string;
  reason: string;
}

export interface TherapistBriefData {
  themes: string[];
  distortions: string[];
  mood_arc: MoodArcPoint[];
  representative_entries: RepresentativeEntry[];
  summary: string;
}

/**
 * Generates a Therapist Bridge PDF from brief data.
 * Excludes entries whose journal_id is in the redactedEntryIds set.
 * Returns Uint8Array of the PDF.
 */
export async function generateTherapistBriefPDF(
  data: TherapistBriefData,
  redactedEntryIds: Set<string> = new Set()
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const pageWidth = 595.28; // A4
  const pageHeight = 841.89;
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;

  let page = doc.addPage([pageWidth, pageHeight]);
  let y = pageHeight - margin;

  const lineHeight = 14;
  const sectionGap = 24;
  const headerSize = 18;
  const subheaderSize = 13;
  const bodySize = 10;

  function checkPageBreak(needed: number) {
    if (y - needed < margin + 40) {
      page = doc.addPage([pageWidth, pageHeight]);
      y = pageHeight - margin;
    }
  }

  function drawText(text: string, size: number, useBold = false, indent = 0) {
    const f = useBold ? fontBold : font;
    const maxWidth = contentWidth - indent;
    const words = text.split(" ");
    let line = "";

    for (const word of words) {
      const testLine = line ? `${line} ${word}` : word;
      const width = f.widthOfTextAtSize(testLine, size);
      if (width > maxWidth && line) {
        checkPageBreak(lineHeight);
        page.drawText(line, {
          x: margin + indent,
          y,
          size,
          font: f,
          color: rgb(0.07, 0.07, 0.07),
        });
        y -= lineHeight;
        line = word;
      } else {
        line = testLine;
      }
    }
    if (line) {
      checkPageBreak(lineHeight);
      page.drawText(line, {
        x: margin + indent,
        y,
        size,
        font: f,
        color: rgb(0.07, 0.07, 0.07),
      });
      y -= lineHeight;
    }
  }

  // Header
  page.drawText("NexoMind Therapist Brief", {
    x: margin,
    y,
    size: headerSize,
    font: fontBold,
    color: rgb(0.07, 0.07, 0.07),
  });
  y -= 28;

  // Disclaimer block
  const disclaimerText =
    "DISCLAIMER: This document is generated by AI-assisted analysis of user journal entries. " +
    "It is not a clinical assessment, diagnosis, or treatment recommendation. " +
    "It is intended as supplementary context for a licensed mental health professional. " +
    "The user has consented to share this information with their therapist.";
  page.drawRectangle({
    x: margin,
    y: y - 60,
    width: contentWidth,
    height: 65,
    color: rgb(0.95, 0.95, 0.92),
  });
  y -= 5;
  drawText(disclaimerText, 8.5);
  y -= sectionGap;

  // Themes section
  checkPageBreak(40);
  drawText("Recurring Themes", subheaderSize, true);
  y -= 4;
  for (const theme of data.themes) {
    drawText(`\u2022 ${theme}`, bodySize, false, 10);
  }
  y -= sectionGap;

  // Distortions section
  checkPageBreak(40);
  drawText("Cognitive Distortions", subheaderSize, true);
  y -= 4;
  for (const distortion of data.distortions) {
    drawText(`\u2022 ${distortion}`, bodySize, false, 10);
  }
  y -= sectionGap;

  // Mood Arc visualization (text-based sparkline representation)
  checkPageBreak(80);
  drawText("Mood Arc (30-day overview)", subheaderSize, true);
  y -= 8;

  if (data.mood_arc.length > 0) {
    // Draw a simple text-based mood arc table
    drawText("Date              Intensity    Clarity", 9, true, 5);
    y -= 2;
    for (const point of data.mood_arc.slice(0, 15)) {
      const dateStr = point.date.slice(0, 10).padEnd(18);
      const intensity = String(point.intensity_score).padEnd(13);
      const clarity = String(point.clarity_score);
      drawText(`${dateStr}${intensity}${clarity}`, 9, false, 5);
    }
    if (data.mood_arc.length > 15) {
      drawText(`... and ${data.mood_arc.length - 15} more data points`, 8, false, 5);
    }
  }
  y -= sectionGap;

  // Representative Entries
  const filteredEntries = data.representative_entries.filter(
    (e) => !redactedEntryIds.has(e.journal_id)
  );

  if (filteredEntries.length > 0) {
    checkPageBreak(60);
    drawText("Representative Entries", subheaderSize, true);
    y -= 4;
    for (const entry of filteredEntries) {
      checkPageBreak(50);
      drawText(`${entry.date.slice(0, 10)} - ${entry.reason}`, bodySize, true, 5);
      drawText(entry.summary, bodySize, false, 10);
      y -= 8;
    }
    y -= sectionGap;
  }

  // Summary
  checkPageBreak(60);
  drawText("Clinical Summary", subheaderSize, true);
  y -= 4;
  drawText(data.summary, bodySize);
  y -= sectionGap;

  // Footer
  const today = new Date().toISOString().slice(0, 10);
  checkPageBreak(30);
  page.drawLine({
    start: { x: margin, y },
    end: { x: pageWidth - margin, y },
    thickness: 0.5,
    color: rgb(0.7, 0.7, 0.7),
  });
  y -= 14;
  page.drawText(`Generated by NexoMind on ${today}`, {
    x: margin,
    y,
    size: 8,
    font,
    color: rgb(0.5, 0.5, 0.5),
  });

  return doc.save();
}
